package com.mahmodhota.worldfood3dadventure.game.match3.model

/**
 * Types of food tiles available in the match-3 game.
 */
enum class FoodTileType {
    // Italy
    PIZZA, PASTA, TOMATO, CHEESE, GELATO, BASIL, SPAGHETTI, LASAGNE, RAVIOLI, GNOCCHI, TIRAMISU,
    
    // Germany
    PRETZEL, BRATWURST, POTATO, APPLE, BREAD, BLACK_FOREST_CAKE,

    // France
    CROISSANT, BAGUETTE, FRENCH_CHEESE, CREPE, MACARON, RATATOUILLE, ECLAIR, SOUFFLE, TARTE_TATIN,

    // Japan
    SUSHI, RAMEN, TEMPURA, ONIGIRI, MOCHI, TAKOYAKI, UDON, MATCHA, DORAYAKI,

    // Mexico
    TACO, BURRITO, GUACAMOLE, NACHOS, CHILI, TAMALE, QUESADILLA, CHURROS, POZOLE,

    // Sudan
    KISRA, FUL_MEDAMES, MULAH, TAGALIA, AGASHE, SAMBUSA, SHAWAYA, GURRASA, ASIDA,

    // Spain
    PAELLA, TORTILLA_ESPANOLA, JAMON_IBERICO, GAZPACHO, CROQUETAS, PATATAS_BRAVAS, PULPO_A_LA_GALLEGA, SANGRIA, CREMA_CATALANA,

    // NEW: USA
    BURGER, FRIES, HOT_DOG, DONUT, PANCAKE, STEAK,
    
    // NEW: UK
    FISH_AND_CHIPS, SCONE, TEA, POT_PIE,
    
    // NEW: China
    DIM_SUM, DUMPLING, FRIED_RICE, PEKING_DUCK, SPRING_ROLL,
    
    // NEW: India
    CURRY, NAAN, BIRYANI, TANDOORI_CHICKEN, GULAB_JAMUN,
    
    // NEW: Brazil
    FEIJOADA, BRIGADEIRO, COXINHA, PADE_QUEIJO,
    
    // NEW: Egypt
    KOSHARY, FALAFEL, SHAWARMA, BAKLAVA,
    
    // NEW: Greece
    GYROS, MOUSSAKA, FETA, OLIVES,
    
    // NEW: Thailand
    PAD_THAI, TOM_YUM, MANGO_STICKY_RICE,
    
    // NEW: Korea
    KIMCHI, BIBIMBAP, BULGOGI,
    
    // NEW: Turkey
    KEBAB, TURKISH_DELIGHT, KOFTE,
    
    // NEW: generic/shared
    COFFEE, MILK, EGG, CORN, FISH, CHICKEN, RICE
}
